import React from 'react';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import ReportsManager from '@/components/reports/ReportsManager';

export const metadata = {
  title: 'Reports Manager - SteelSmart AI Marketplace',
  description: 'View and manage analysis and recommendation reports generated by SteelSmart AI tools.',
};

export default function ReportsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-gray-900 mb-4">Reports Manager</h1>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              View and manage all your analysis and recommendation reports generated by SteelSmart AI tools.
            </p>
          </div>
          
          <ReportsManager />
        </div>
      </main>
      <Footer />
    </div>
  );
}























